# Generated by Django 3.2.16 on 2022-12-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loginlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('1', 'petrol'), ('2', 'diesel'), ('3', 'cng'), ('4', 'bio-diesel')], max_length=4)),
                ('car_images', models.FileField(upload_to='E:/pythonproject/')),
                ('price_per_hour', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
