# Generated by Django 3.2.16 on 2022-12-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('1', 'petrol'), ('2', 'diesel'), ('3', 'cng'), ('4', 'bio-diesel')], max_length=4)),
                ('car_images', models.FileField(upload_to='E:\\pythonproject\\django\\django rest framework\\VehicleRentalApi')),
                ('price_per_hour', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
